server:
  port: 92
eureka:
  client:
    service-url:
      defaultZone: http://eureka-A:8080/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: provider



